version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12

    environment:
      TEST_RESULTS: /tmp/test-results
      GO111MODULE: "on"

    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS
      - restore_cache:
      # Read about caching dependencies: https://circleci.com/docs/2.0/caching/
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}

      - run: go get github.com/jstemmer/go-junit-report
      - run: go get ./...
      - run:
          name: Run unit tests

          # store the results of our tests in the $TEST_RESULTS directory
          command: |
            PACKAGE_NAMES=$(go list ./... | circleci tests split --split-by=timings --timings-type=classname)
            gotestsum --junitfile ${TEST_RESULTS}/gotestsum-report.xml -- $PACKAGE_NAMES

      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"

      - store_artifacts: # Upload test summary for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: /tmp/test-results
          destination: raw-test-output

      - store_test_results: # Upload test results for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: /tmp/test-results

workflows:
  version: 2
  build-workflow:
    jobs:
      - build
